version: '2'
services:
  espfsampleapplication-app:
    image: espfsampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://espfsampleapplication-mysql:3306/espfsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9080:9080
  espfsampleapplication-mysql:
    extends:
      file: mysql.yml
      service: espfsampleapplication-mysql
